#!/bin/python3
''' tool to parse Valgrind XML files '''
import os
import argparse

from vxml import VXMLReportTool

parser = argparse.ArgumentParser(description='Show Valgrind Summary')
parser.add_argument('-r', '--reverse', action='store_true',
                    default=False, help='summary in reverse')
parser.add_argument('path', nargs='?', default=os.getcwd(), help='path')

DEFAULT_CONFIG = 'vxml-config.yaml'

def main():
    ''' main '''
    args = parser.parse_args()
    path = args.path
    
    report_tool = VXMLReportTool()
    report_tool.setup(path)

    if args.reverse:
        report_tool.print_reports(reverse=True)
    else:
        report_tool.print_reports()


if __name__ == '__main__':
    main()
